#!/bin/sh
os=$(lsb_release -is)
if [ "$os" = "Ubuntu" ] || [ "$os" = "Debian" ]; then
  sudo apt update
  sudo apt install fish -y
fi

DFD=$HOME/.dotfiles

sudo ln -sf "$DFD/update_dotfiles" /usr/local/bin/update_dotfiles

sudo ln -sf "$DFD/update_dotfiles.service" /etc/systemd/system/update_dotfiles.service

sudo ln -sf "$DFD/update_dotfiles.timer" /etc/systemd/system/update_dotfiles.timer

sudo systemctl daemon-reload

sudo systemctl enable --now update_dotfiles.timer
