#!/bin/sh
os=$(lsb_release -is)
if ([ "$os" = "Ubuntu" ] || [ "$os" = "Debian" ]) && [ -z "$(which fish)" ]; then
  echo fish not installed, installing...
  sudo apt update
  sudo apt install fish hub thefuck fzf -y
fi

wf=$(which fish)
fp="${wf:-/usr/local/bin/fish}"
if [ "$SHELL" != "$fp" ]; then
  echo fish not default shell, changing...
  which zsh | sudo tee -a /etc/shells
  sudo chsh m -s "$fp"
fi

if [ ! -d "$HOME/.local/share/omf" ]; then
  curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish
fi

DFD=$HOME/.dotfiles

sudo ln -sf "$DFD/update_dotfiles" /usr/local/bin/update_dotfiles

sudo ln -sf "$DFD/update_dotfiles.service" /etc/systemd/system/update_dotfiles.service

sudo ln -sf "$DFD/update_dotfiles.timer" /etc/systemd/system/update_dotfiles.timer

sudo systemctl daemon-reload

sudo systemctl enable --now update_dotfiles.timer
